### ISSUE TITLE
Homepage banner needs new design

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/insights.ubuntu.com#107]
Perhaps a photo to match the other group pages?

**Comment by spencerbygraves** [comment]
@pmahnke Good idea. We looked at the insights pages in the Suru workshop when thinking about how to better use the folds pattern with images. [I've made an issue to look into it](https://github.com/ubuntudesign/web-squad/issues/334), I think it would be good to add a homepage banner to the new set, rather than match the existing.

**Comment by anthonydillon** [comment]
This was done.
